- name: Install python3
  apt:
    name: "{{python_version_meta.Debian[python_version]}}"
    update_cache: yes

# The virtual environment was not created successfully because ensurepip is not
# available.  On Debian/Ubuntu systems, you need to install the python3-venv
- name: Install venv 
  apt:
    name: python3-venv