- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
    
- name: Upgrade pip3
  shell: python3 -m pip install --upgrade pip

- name: Check Python version
  shell: |
    sudo sh -c "python2 -V 2>> /data/logs/install_version.txt"
    sudo sh -c "python3 -V 1>> /data/logs/install_version.txt"

## prepare python application installation
- name: Create venv environment
  shell: python3 -m venv --system-site-packages {{python_venv_path}}  

- name: copy python_env.sh
  template:
    src: python_env.sh
    dest: /etc/profile.d

- name: Upgrade pip on venv
  shell: "{{python_venv_path}}"/bin/pip install --upgrade pip

# Python application installation
- name: Install Python applications
  include_tasks: apps/{{item}}.yml
  with_items: "{{python_applications}}"
  when: python_applications is defined and python_applications != "" 
