- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Check Python version
  shell: |
    sudo sh -c "python2 -V 2>> /data/logs/install_version.txt"
    sudo sh -c "python3 -V 1>> /data/logs/install_version.txt"
