- name: Get system python version
  shell: >
    python3 --version |awk '{print $2}' |cut -c1-3
  register: python_sys_version

- debug: var=python_sys_version.stdout

- fail: msg="The Python version is lower than the system's own Python,select a higher Python version!"
  when: python_version is version(python_sys_version.stdout,"<")

- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
  
- name: Switch to Python Version
  shell: |
    update-alternatives --install /usr/bin/python python /usr/bin/python{{python_version}} 1000
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python{{python_version}} 1000
    
- name: Upgrade pip3
  shell: python3 -m pip install --upgrade pip
  args:
    executable: /bin/bash 

- name: Check Python version
  shell: |
    sudo echo "python3 version:" $(python3 --version) |sudo tee -a /data/logs/install_version.txt
    sudo echo "pip version:" $(pip3 --version) |sudo tee -a /data/logs/install_version.txt

# Python application installation
- name: Install Python applications
  include_tasks: apps/{{item}}.yml
  with_items: "{{python_applications}}"
  when: python_applications is defined and python_applications != "" 
