- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: copy python_alias.sh
  template:
    src: python_alias.sh
    dest: /etc/profile.d
    
- name: Upgrade pip3
  shell: |
    source /etc/profile.d/python_alias.sh 
    python3 -m pip install --upgrade pip
  args:
    executable: /bin/bash 

- name: Check Python version
  shell: |
    [ -f /etc/profile.d/python_scl.sh ] && source /etc/profile.d/python_scl.sh
    sudo echo "python3 version:" $(python3 --version) |sudo tee -a /data/logs/install_version.txt
    sudo echo "pip version:" $(pip3 --version) |sudo tee -a /data/logs/install_version.txt

# Python application installation
- name: Install Python applications
  include_tasks: apps/{{item}}.yml
  with_items: "{{python_applications}}"
  when: python_applications is defined and python_applications != "" 
