- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
  
- name: Upgrade pip3
  shell: python3 -m pip install --upgrade pip

- name: Check Python version
  shell: |
    sudo sh -c "python2 -V 2>> /data/logs/install_version.txt"
    sudo sh -c "python3 -V 1>> /data/logs/install_version.txt"
    
# Python application installation
- name: Install Python applications
  include_tasks: apps_{{item}}.yml
  with_items: "{{python_applications}}"
  when: python_applications is defined and python_applications != ""
