- name: Install python3
  yum:
    name: [python3,python3-libs,python3-pip,python3-setuptools]

# make install    
# - name: Install GCC
#   yum:
#     name: [gcc,]

# # yum install zlib-devel bzip2-devel openssl-devel python-devel kernel-devel libffi-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make

# - name: Configure and make make install
#   shell: | 
#     ./configure  
#     make && make install
#   args: 
#     chdir: /tmp
    

  
  

  

