- name: Uninstall ansible
  yum: 
    name: ansible
    state: absent
    
  when: ansible_os_family == "RedHat"

- name: Uninstall ansible
  apt: 
    name: ansible
    state: absent
    autoclean: yes
    autoremove: yes
  when: ansible_os_family == "Debian"

- name: Install ansible and exra modules
  pip:
    name: [ansible,requests,docker,PyMySQL,psycopg2-binary]
    executable: pip3
  
- name: Run ansible cli for create log file
  shell: ansible --version

- name: Create link for ansible
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /usr/local/bin/ansible,dest: /usr/bin/ansible}

- name: Check ansible version
  shell: sudo echo $(ansible  --version |sed -n 1p) |sudo tee -a /data/logs/install_version.txt