- name: Install Ansible and exra modules
  pip:
    name: [requests,docker,PyMySQL,psycopg2-binary]
    executable: pip3

- name: Create link for ansible
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /etc/ansible/ansible.cfg,dest: /data/config/ansible.cfg}

- block:
  - name: Get ansible cli
    stat: path=/usr/bin/ansible
    register: ansible_stat

  - name: Check whether ansible exists
    fail:
      msg: "ansible was not install successful"
    when: not ansible_stat.stat.exists

- name: Check ansible version
  shell: sudo echo $(ansible  --version |sed -n 1p) |sudo tee -a /data/logs/install_version.txt