- name: Install Ansible and exra modules
  pip:
    name: [ansible,requests,docker,PyMySQL,psycopg2-binary]
    executable: pip3

- name: Create link for ansible
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /etc/ansible,dest: /data/config/}

- name: Check ansible version
  shell: sudo echo $(ansible  --version |sed -n 1p) |sudo tee -a /data/logs/install_version.txt