- name: Create python_applications dir on venv
  file:
    path: "{{python_venv_path}}/{{python_applications}}"
    state: directory

- name: Install Django
  pip: 
    name: django
    virtualenv: "{{python_venv_path}}"
    virtualenv_command: python3 -m venv --system-site-packages "{{python_venv_path}}"
    
- name: copy python_env.sh
  template:
    src: python_env.sh 
    dest: /etc/profile.d

- name: Upgrade pip on venv
  shell: >
    {{python_venv_path}}/bin/pip install --upgrade pip

- name: Create Demo Project
  shell: |
    rm -rf django_project
    {{python_venv_path}}/bin/django-admin startproject django_project
  args:
    chdir: "{{python_venv_path}}/{{python_applications}}"

- name: Create link for django
  file: 
    src: '{{python_venv_path}}/{{python_applications}}/'
    dest: '/data/wwwroot/'
    state: link
    force: yes

- name: config uwsgi
  copy:
   src: django.ini
   dest: /etc/uwsgi/django.ini
   owner: uwsgi
   group: uwsgi

- name: copy Nginx config
  copy:
    src: django.conf
    dest: /etc/nginx/conf.d/default.conf
    force: yes

- name: Restart uwsgi and Nginx
  service: 
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - uwsgi
    - nginx

- name: Check django version
  shell: sudo echo "django version:" $(django-admin  version) |sudo tee -a /data/logs/install_version.txt

- name: Check uwsgi Service
  shell: systemctl status uwsgi | grep Active*
  register: check_uwsgi_service
  notify: check_uwsgi_service