# prepare_installation
- name: Create python_applications dir on venv
  file:
    path: "{{python_venv_path}}/django"
    state: directory
  
- name: Upgrade pip3 on venv
  shell: |
    python3 -m venv --system-site-packages "{{python_venv_path}}/django"
    "{{python_venv_path}}/django"/bin/python3 -m pip install --upgrade pip
    
## install apps
- name: Install Django and uwsgi
  pip: 
    name: "{{item}}"
    virtualenv: "{{python_venv_path}}/django"
    virtualenv_command: python3 -m venv --system-site-packages "{{python_venv_path}}/django"
  with_items:
    - django
    - uwsgi
    
- name: Create Demo Project
  shell: |
    rm -rf django_project
    ./bin/django-admin startproject django_project
  args:
    chdir: "{{python_venv_path}}/django"

## configure
- name: Create link for django
  file: 
    src: '{{python_venv_path}}/django/'
    dest: '/data/wwwroot/django'
    state: link
    force: yes
      
- name: Configure uwsgi
  template:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    force: yes
  with_items:
    - {src: django.ini,dest: /data/apps/django/django.ini}
    - {src: django_app.service,dest: /lib/systemd/system/django.service}

- name: Open Internet access
  lineinfile:
      dest: "{{python_venv_path}}/django/django_project/django_project/settings.py"
      regexp: "^ALLOWED_HOSTS .*"
      line: "ALLOWED_HOSTS = ['*']"
      backrefs: yes  

- name: Restart django and Nginx
  service: 
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - django
    - nginx

# check 
- name: Check django version
  shell: sudo echo "django version:" $({{python_venv_path}}/django/bin/django-admin  version) |sudo tee -a /data/logs/install_version.txt

- name: Check django Service
  shell: systemctl status django | grep Active*
  register: check_django_service
  notify: check_django_service