- name: Install tensorflow
  pip: 
    name: tensorflow
    virtualenv: "{{python_venv_path}}"
    virtualenv_command: python3 -m venv --system-site-packages "{{python_venv_path}}"

- name: Upgrade pip on venv
  shell: >
    {{python_venv_path}}/bin/pip install --upgrade pip

- name: Copy python_env.sh
  template:
    src: python_env.sh 
    dest: /etc/profile.d
    
- name: Copy tensorflow.service file
  copy:
    src: python_app.service.jinja2
    dest: /lib/systemd/system/tensorflow.service

- name: restatrt and enabled tensorflow
  service:
    name: tensorflow
    state: restarted
    enabled: yes
 
- name: Check tensorflow version
  shell: sudo echo "tensorflow version:" $(tensorboard --version_tb) |sudo tee -a /data/logs/install_version.txt


  




