- name: Install tensorflow
  pip: 
    name: tensorflow
    virtualenv: "{{python_venv_path}}/{{python_applications}}"
    virtualenv_command: python3 -m venv --system-site-packages "{{python_venv_path}}/{{python_applications}}"

- name: Copy python_env.sh and tensorflow.service file 
  template:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - {src: python_env.sh,dest: /etc/profile.d}
    - {src: tensorflow_app.service,dest: /lib/systemd/system/tensorflow.service}

- name: Upgrade pip on venv
  shell: >
    {{python_venv_path}}/{{python_applications}}/bin/pip install --upgrade pip

- name: restatrt and enabled tensorflow
  service:
    name: tensorflow
    state: restarted
    enabled: yes
 
- name: Check tensorflow version
  shell: sudo echo "tensorflow version:" $(tensorboard --version_tb) |sudo tee -a /data/logs/install_version.txt
  

  




