- name: Install tensorflow
  pip: 
    name: tensorflow
    virtualenv: "{{python_venv_path}}"
    virtualenv_command: python3 -m venv --system-site-packages "{{python_venv_path}}"

- name: copy python_env.sh
  template:
    src: python_env.sh 
    dest: /etc/profile.d
    
- name: Copy tensorboard.py
  copy:
    src: tensorflow_test.py
    dest: {{python_venv_path}}/tensorboard.py

- name: Run tensorboard.py and Strarted tensorboard
  shell: |
    source {{python_venv_path}}/bin/activate && python {{python_venv_path}}/tensorboard.py
    tensorboard --logdir=logs/fit --bind_all --port {{python_applications_tensorflow.port}}
    deactivate

- name: Check tensorflow version
  shell: sudo echo "tensorflow version:" $(tensorboard --version_tb) |sudo tee -a /data/logs/install_version.txt


  




